languageCode  = "en-us"
title         = "Reni's Macarons"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = "#banner"
    weight  = 1
  [[menu.nav]]
    name    = "Prices"
    URL     = "#prices"
    weight  = 2
  [[menu.nav]]
    name    = "The Team"
    URL     = "#people"
    weight  = 3
  [[menu.nav]]
    name    = "Locations"
    URL     = "#location"
    weight  = 4
  # [[menu.nav]]
  #   name    = "FAQs"
  #   URL     = "#faqs"
  #   weight  = 5
  [[menu.nav]]
    name    = "Reni's Macarons"
    URL     = "#macarons"
    weight  = 6
